<?php

/**
 * BaseEtat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property boolean $disponible
 * @property Doctrine_Collection $Stock
 * 
 * @method string              getNom()        Returns the current record's "nom" value
 * @method boolean             getDisponible() Returns the current record's "disponible" value
 * @method Doctrine_Collection getStock()      Returns the current record's "Stock" collection
 * @method Etat                setNom()        Sets the current record's "nom" value
 * @method Etat                setDisponible() Sets the current record's "disponible" value
 * @method Etat                setStock()      Sets the current record's "Stock" collection
 * 
 * @package    gigm-materiel
 * @subpackage model
 * @author     Emilien Kenler
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEtat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('etat');
        $this->hasColumn('nom', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('disponible', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Stock', array(
             'local' => 'id',
             'foreign' => 'etat_id'));
    }
}