<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $login_utc
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()    Returns the current record's "user_id" value
 * @method string      getLoginUtc()  Returns the current record's "login_utc" value
 * @method sfGuardUser getUser()      Returns the current record's "User" value
 * @method Profile     setUserId()    Sets the current record's "user_id" value
 * @method Profile     setLoginUtc()  Sets the current record's "login_utc" value
 * @method Profile     setUser()      Sets the current record's "User" value
 * 
 * @package    gigm-materiel
 * @subpackage model
 * @author     Emilien Kenler
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('login_utc', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}