<?php

/**
 * BaseAssemblage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $materiel_id
 * @property integer $equipement_id
 * @property integer $nombre
 * @property Materiel $Materiel
 * @property Equipement $Equipement
 * 
 * @method integer    getMaterielId()    Returns the current record's "materiel_id" value
 * @method integer    getEquipementId()  Returns the current record's "equipement_id" value
 * @method integer    getNombre()        Returns the current record's "nombre" value
 * @method Materiel   getMateriel()      Returns the current record's "Materiel" value
 * @method Equipement getEquipement()    Returns the current record's "Equipement" value
 * @method Assemblage setMaterielId()    Sets the current record's "materiel_id" value
 * @method Assemblage setEquipementId()  Sets the current record's "equipement_id" value
 * @method Assemblage setNombre()        Sets the current record's "nombre" value
 * @method Assemblage setMateriel()      Sets the current record's "Materiel" value
 * @method Assemblage setEquipement()    Sets the current record's "Equipement" value
 * 
 * @package    gigm-materiel
 * @subpackage model
 * @author     Emilien Kenler
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAssemblage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('assemblage');
        $this->hasColumn('materiel_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('equipement_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nombre', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Materiel', array(
             'local' => 'materiel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Equipement', array(
             'local' => 'equipement_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}