generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Etat
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          etat
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=nom, disponible]
        title: Liste des états
      filter:  ~
      form:    ~
      edit:
        title: Modification d'un état
      new:
        title: Ajout d'un état
