generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Equipement
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          equipement
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=nom, description]
        title: Liste des équipements
      filter:  ~
      form:    ~
      edit:
        title: Modification d'un équipement
      new:
        title: Ajout d'un équipement
