<?php

/**
 * Assemblage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gigm-materiel
 * @subpackage model
 * @author     Emilien Kenler
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Assemblage extends BaseAssemblage
{

  public function assembler($form,$emprunt)
  {
    $materiel_id = $form->getValue('materiel_id');
    $equipement_id = $form->getValue('equipement_id');
    $nombre = $form->getValue('nombre');

    $emprunt->rendre();

    $dispo = StockTable::getInstance()->findOneByMaterielIdAndEtatId($materiel_id,1);
    if($dispo && $dispo->getNombre() >= $nombre)
    {
      $form->save();
      $dispo->addNombre(-($nombre));
      $dispo->save();

      $assemble = StockTable::getInstance()->findOneByMaterielIdAndEtatId($materiel_id,5);
      if(!$assemble)
      {
        $assemble = new Stock();
        $assemble->setNombre($nombre);
        $assemble->setMaterielId($materiel_id);
        $assemble->setEtatId(5);
      }
      else
      {
        $assemble->addNombre($nombre);
      }
      $assemble->save();
      return true;
    }
    else
      return false;
  }

}
