<?php

/**
 * EquipementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Equipement');
    }
}