generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Emprunt
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          emprunt
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        user: { label: "Utilisateur" }
      list:
        display: [=materiel, user, nombre, rendu]
        title: Liste des emprunts
      filter:  ~
      form:    ~
      edit:
        title: Modification d'un emprunt
      new:
        title: Nouvel emprunt