generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Assemblage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          assemblage
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=materiel, equipement, nombre]
        title: Liste des assemblages
      filter:  ~
      form:    ~
      edit:
        title: Modification d'un assemblage
      new:
        title: Ajout d'un assemblage
