generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Materiel
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                Materiaux
    route_prefix:          materiel
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        reference: { help: "Référence du composant" }
      list:
        display: [=nom, reference, description]
        title: Liste du matériel
      filter:  ~
      form:    ~
      edit:
        title: Modification d'un matériel
      new:
        title: Ajout d'un matériel